// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzU4L0VFVEMIdOsYerl2Jzg_Z7XOQGlGc',
    appId: '1:91084151412:web:c5b37f839797443edf0f21',
    messagingSenderId: '91084151412',
    projectId: 'completefirebase-8cf35',
    authDomain: 'completefirebase-8cf35.firebaseapp.com',
    storageBucket: 'completefirebase-8cf35.appspot.com',
    measurementId: 'G-N2G3V2K0CD',
    databaseURL: "https://completefirebase-8cf35-default-rtdb.firebaseio.com",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcXegsiju11EIpTfPWBBlOoK7Uns6gSJs',
    appId: '1:91084151412:android:94f33dcb19648751df0f21',
    messagingSenderId: '91084151412',
    projectId: 'completefirebase-8cf35',
    storageBucket: 'completefirebase-8cf35.appspot.com',
    databaseURL: "https://completefirebase-8cf35-default-rtdb.firebaseio.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxzxDC8QGa77JbvKiTZohj84ZREuq2VeU',
    appId: '1:91084151412:ios:d5ab0bf0ceb3e8ebdf0f21',
    messagingSenderId: '91084151412',
    projectId: 'completefirebase-8cf35',
    storageBucket: 'completefirebase-8cf35.appspot.com',
    iosBundleId: 'com.example.firebaseTech',
    databaseURL: "https://completefirebase-8cf35-default-rtdb.firebaseio.com",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxzxDC8QGa77JbvKiTZohj84ZREuq2VeU',
    appId: '1:91084151412:ios:a598c9651faad83bdf0f21',
    messagingSenderId: '91084151412',
    projectId: 'completefirebase-8cf35',
    storageBucket: 'completefirebase-8cf35.appspot.com',
    iosBundleId: 'com.example.firebaseTech.RunnerTests',
    databaseURL: "https://completefirebase-8cf35-default-rtdb.firebaseio.com",
  );
}
